DROP TABLE IF EXISTS Businesses, Categories, CheckinTimeWindow, Cities, Business_Category, Business_Checkin; 

CREATE TABLE IF NOT EXISTS Businesses(BusinessId VARCHAR(255) PRIMARY KEY, 
    Name TEXT, 
    FullAddress MEDIUMTEXT,
    City VARCHAR(255),
    State VARCHAR(20),
    Latitude FLOAT,
    Longitude FLOAT) 
    ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS Categories(Category VARCHAR(255) PRIMARY KEY) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS Business_Category(id INT NOT NULL AUTO_INCREMENT,
	BusinessId VARCHAR(255), 
    State VARCHAR(20),
	Category VARCHAR(255),
	PRIMARY KEY (id,State))
    ENGINE=InnoDB, 
    AUTO_INCREMENT=1;
ALTER TABLE Business_Category
	PARTITION BY LIST COLUMNS (State) 
(
   PARTITION p01BW VALUES IN ('BW'),
   PARTITION p02CB VALUES IN ('SCB'),
   PARTITION p03MLN VALUES IN ('MLN'),
   PARTITION p04SC VALUES IN ('SC'),
   PARTITION p05IL VALUES IN ('IL'),
   PARTITION p06ELN VALUES IN ('ELN'),
   PARTITION p07NV VALUES IN ('NV'),
   PARTITION p08QC VALUES IN ('QC'),
   PARTITION p09WI VALUES IN ('WI'),
   PARTITION p10AZ VALUES IN ('AZ'),
   PARTITION p11CA VALUES IN ('CA'),
   PARTITION p12KHL VALUES IN ('KHL'),
   PARTITION p13ON VALUES IN ('ON'),
   PARTITION p14FIF VALUES IN ('FIF'),
   PARTITION p15WA VALUES IN ('WA'),
   PARTITION p16EDH VALUES IN ('EDH'),
   PARTITION p17PA VALUES IN ('PA'),
   PARTITION p18NC VALUES IN ('NC')
);
CREATE TABLE IF NOT EXISTS Cities(City VARCHAR(255) PRIMARY KEY,
	State TINYTEXT) 
	ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CheckinTimeWindow(HourWeekTimeWindow VARCHAR(255) PRIMARY KEY) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS Business_Checkin(id INT NOT NULL AUTO_INCREMENT,
	HourWeekTimeWindow VARCHAR(255),
	Hour VARCHAR(2),
	Week VARCHAR(1),
	BusinessId VARCHAR(255), 
	Count INT,
	PRIMARY KEY (id,Week))
    ENGINE=InnoDB, 
    AUTO_INCREMENT=1;
ALTER TABLE Business_Checkin
	PARTITION BY LIST COLUMNS (Week) 
(
   PARTITION p0 VALUES IN ('0'),
   PARTITION p1 VALUES IN ('1'),
   PARTITION p2 VALUES IN ('2'),
   PARTITION p3 VALUES IN ('3'),
   PARTITION p4 VALUES IN ('4'),
   PARTITION p5 VALUES IN ('5'),
   PARTITION p6 VALUES IN ('6')
);